name: ucsbaicopsymposium2024
recipe: drupal10
config:
  webroot: web
  php: '8.1'
services:
  appserver:
    xdebug: debug
    config:
      php: .vscode/php.ini
    build_as_root:
      - chmod +x /app/extract-files.sh  # Make sure the script is executable
      - /app/extract-files.sh  # Run your custom script
    build:
      - composer install
  database:
    type: mysql:5.7
    portforward: true
    build_as_root:
      - chmod +x /app/import-db.sh  # Make sure the import script is executable
      - /app/import-db.sh  # Run the import script