<?php

/**
 * @file
 * Contains grid_photo_items.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ucsb_grid_photo_items_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.grid_photo_items':
      $output = '';
      $output .= '<h3>' . t('UCSB Grid Photo Items') . '</h3>';
      $output .= '<p>' . t('Grid Photo Items module adds an additional paragraph type for the Grid and enables users to add photos to the front side of the grid cards') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_preprocess_paragraph().
 */
function ucsb_grid_photo_items_preprocess_paragraph(&$variables) {
  $is_admin = \Drupal::service('router.admin_context')->isAdminRoute();
  $variables['is_admin_route'] = $is_admin;
}

/**
 * Implements hook_theme().
 */
function ucsb_grid_photo_items_theme($existing, $type, $theme, $path) {
  
  return [
    'paragraph__grid_photo_item' => [
      'render element' => 'element',
      'template' => 'paragraph--grid-photo-item',
      'base hook' => 'paragraph'
    ],
  ];
}



