<?php

/**
 * @file
 * Contains ucsb_power_bi.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ucsb_power_bi_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ucsb_power_bi module.
    case 'help.page.ucsb_power_bi':
      $output = '';
      $output .= '<h3>' . t('About UCSB Power BI') . '</h3>';
      $output .= '<p>' . t('Integration with PowerBI.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_preprocess_page().
 */
function ucsb_power_bi_preprocess_page(&$variables) {
  // Add Microsoft PowerBI JS client library.
  $variables['#attached']['library'][] = 'ucsb_power_bi/ucsb_power_bi-client';
  // Add module-specific JS customizations.
  $variables['#attached']['library'][] = 'ucsb_power_bi/ucsb_power_bi-customizer';
}
